// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSsP9iljOgX5QBczCBShz592vW3TfxAcc',
    appId: '1:357117924366:web:80aedc4e4a253d7833985f',
    messagingSenderId: '357117924366',
    projectId: 'contentcreator-9774f',
    authDomain: 'contentcreator-9774f.firebaseapp.com',
    storageBucket: 'contentcreator-9774f.firebasestorage.app',
    measurementId: 'G-7S61WEN001',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1f8NHMBtiqKmsXB2zKKHoPnhYwaPe4Y',
    appId: '1:357117924366:android:abc0c8dec54fde3133985f',
    messagingSenderId: '357117924366',
    projectId: 'contentcreator-9774f',
    storageBucket: 'contentcreator-9774f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSAZTp0pl8q2MBYmeccFG6pu2AT5UIgbo',
    appId: '1:357117924366:ios:fea02b1b78b2396e33985f',
    messagingSenderId: '357117924366',
    projectId: 'contentcreator-9774f',
    storageBucket: 'contentcreator-9774f.firebasestorage.app',
    iosBundleId: 'com.example.barcontent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSAZTp0pl8q2MBYmeccFG6pu2AT5UIgbo',
    appId: '1:357117924366:ios:fea02b1b78b2396e33985f',
    messagingSenderId: '357117924366',
    projectId: 'contentcreator-9774f',
    storageBucket: 'contentcreator-9774f.firebasestorage.app',
    iosBundleId: 'com.example.barcontent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSsP9iljOgX5QBczCBShz592vW3TfxAcc',
    appId: '1:357117924366:web:c3ddfc0627faed5933985f',
    messagingSenderId: '357117924366',
    projectId: 'contentcreator-9774f',
    authDomain: 'contentcreator-9774f.firebaseapp.com',
    storageBucket: 'contentcreator-9774f.firebasestorage.app',
    measurementId: 'G-53QVKEGJVM',
  );
}
